---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fluxa.fluxa.io
  resources:
  - fluxaservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxa.fluxa.io
  resources:
  - fluxaservices/finalizers
  verbs:
  - update
- apiGroups:
  - fluxa.fluxa.io
  resources:
  - fluxaservices/status
  verbs:
  - get
  - patch
  - update
